#!/bin/sh

sudo apt-get update
sudo apt-get install -y \
  libbz2-dev \
  libsqlite3-dev \
  libxml2-dev \
  libxslt-dev

curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash

cat << "EOF" >> ~/.bash_profile

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
EOF

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# install supported python versions and create a virtualenv
pyenv install 3.6.0
pyenv install 3.5.2
pyenv install 3.4.5
pyenv install 2.7.13
pyenv virtualenv 3.6.0 eemeter3.6.0

cd /vagrant
git clone https://github.com/openeemeter/eemeter.git

cd /vagrant/eemeter
pyenv local eemeter3.6.0 3.6.0 3.5.2 3.4.5 2.7.13
pip install -e .
pip install -r dev_requirements.txt
pip install notebook

echo 'cd /vagrant/eemeter' >> ~/.bash_profile
